// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/social-ads/Identity.tsx": () => import("../components/mockups/social-ads/Identity.tsx"),
  "./components/mockups/social-ads/LinkedIn.tsx": () => import("../components/mockups/social-ads/LinkedIn.tsx"),
  "./components/mockups/social-ads/Outcome.tsx": () => import("../components/mockups/social-ads/Outcome.tsx"),
  "./components/mockups/social-ads/PainPoint.tsx": () => import("../components/mockups/social-ads/PainPoint.tsx")
};
